### ISSUE TITLE
[cli-jmx] make server-name configurable

### ISSUE THREAD

**Issue by jdanekrh** [rh-messaging/cli-java#36]
currenly, the value `amq` is hardcoded.

**Comment by michalxo** [comment]
This is done already. "amq" is a default value. Use --broker-name "amq-ha2-brk".

**Comment by michalxo** [comment]
Also I think cli-jmx has not yet been opensourced, was it?

**Comment by jdanekrh** [comment]
No, it is not opensourced here yet.

**Comment by michalxo** [comment]
Marking this one as invalid. Feel free to reopen if needed, but amqx (cli-jmx) handles artemis name without problems. Also, cli-jmx is not part of this project, is it?
